version: '2'

services:
  dokuwiki:
    file: ./Dockerfile
    ports:
      - "8000:80"
    volumes:
      - dokuwiki-data:/var/dokuwiki-storage
    container_name:
      dokuwiki      

volumes:
  dokuwiki-data:
    driver: local
  